export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_PHOTO_DATA: 'SET_PHOTO_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
	RESET_PHOTO_DATA: 'RESET_PHOTO_DATA',
	ADD_LIKE: 'ADD_LIKE',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
